# Dockerfile para desarrollo
FROM node:22-alpine3.19

RUN mkdir /home/node/app/ && chown -R node:node /home/node/app

WORKDIR /home/node/app
COPY package*.json ./

RUN npm install

COPY . .

CMD npm run start:dev
