services:
  # api:
  #   image: "node:22-alpine3.19"
  #   command: "nest run start:dev"
  #   user: node
  #   working_dir: /home/node/nest
  #   volumes:
  #     - .:/home/node/nest
  #   environment:
  #     - NODE_ENV=development
  #     - ARCHIVO_ENV=development
  #   ports:
  #     - "3000:4000"
  
  # mysql:
  #   image: mysql:8.0.39-debian
  #   ports:
  #     - "3307:${PORT_DB}"
  #   volumes:
  #     - ./sql:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  mysql:
    image: mysql:8.0.39-debian
    ports:
      - "3307:3306"
    volumes:
      - ./sql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: grupo-6