services:
  api:
    image: "node:${VERSION_NODE}"
    command: "npm run start:dev"
    user: node
    working_dir: /home/node/nest
    volumes:
      - .:/home/node/nest
    environment:
      - PUERTO_NEST=${PUERTO_NEST}
      - PUERTO_DB=${PUERTO_DB}
      - CLAVE_ROOT_DB=${CLAVE_ROOT_DB}
      - NOMBRE_DB=${NOMBRE_DB}
      - USUARIO_DB=${USUARIO_DB}
      - RUTA_DB=${RUTA_DB}
    ports:
      - "${PUERTO_NEST}:3000"
    depends_on:
      - mysql

  mysql:
    image: mysql:${VERSION_DB}
    environment:
      - MYSQL_ROOT_PASSWORD=${CLAVE_ROOT_DB}
    volumes:
      - ./sql:/var/lib/mysql
    ports:
      - "${PUERTO_DB}:3306"

  flyway:
    image: flyway/flyway:${VERSION_FLYWAY}
    volumes:
      - ./src/BBDD:/flyway/sql
    environment:
      FLYWAY_URL: jdbc:mysql://${RUTA_DB}:${PUERTO_DB}/${NOMBRE_DB}?allowPublicKeyRetrieval=true
      FLYWAY_USER: ${USUARIO_DB}
      FLYWAY_PASSWORD: ${CLAVE_ROOT_DB}
    entrypoint: ["flyway", "-connectRetries=60", "migrate"]
    depends_on: 
      - mysql
