services:
  api:
    image: ncarvajalg/grupo-6-backend-dev:v2.0.0

    volumes:
      - .:/home/node/app

    environment:
      - NODE_ENV=development # Define el entorno como desarrollo
    
    ports:
      - "3000:4000"
    