services:
  mysql:
    image: mysql:${VERSION_DB}
    ports:
      - "3307:${PUERTO_DB}"
    volumes:
      - ./sql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${CLAVE_ROOT_DB}

  flyway:
    image: flyway/flyway:${VERSION_FLYWAY}
    volumes:
      - ./src/BBDD/:/flyway/sql
    command: -url=jdbc:mysql://${RUTA_DB}:${PUERTO_DB}/${NOMBRE_DB}?allowPublicKeyRetrieval=true -user=${USUARIO_DB} -password=${CLAVE_ROOT_DB} -connectRetries=60 migrate    

  # api:
  #   image: "node:${VERSION_NODE}"

  #   command: "nest run start:dev"

  #   user: node

  #   working_dir: /home/node/nest

  #   volumes:
  #     - .:/home/node/nest

  #   environment:
  #     - PUERTO_NESTJS=${PUERTO_NEST}
  #     - DB_HOST=${RUTA-DB}
  #     - DB_PORT=${PUERTO_DB}
  #     - DB_USER=${USUARIO_DB}
  #     - DB_PASS=${CLAVE_ROOT_DB}
  #     - DB_NAME=${NOMBRE_DB}

  #   ports:
  #     - "3000:${PUERTO_NEST}"
  
  

  