services:
  api:
    image: ncarvajalg/grupo-6-backend:v5.0.3
    container_name: g6_backend

    environment:
      - ARCHIVO_ENV=production
      - NODE_ENV=production

    ports:
      - "3000:${PUERTO_NEST}"

    depends_on:
      - mysql

    env_file:
      - .env
    
  mysql:
    image: mysql:8.0.39-debian
    container_name: g6_backend_bd

    ports:
      - "3306:${PUERTO_DB}"

    volumes:
      - ./sql:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: grupo-6
      MYSQL_DATABASE: paginas_selectas
      
    env_file:
      - .env
    
  flyway:
    image: flyway/flyway:${VERSION_FLYWAY}
    volumes:
      - ./BBDD:/flyway/sql
    environment:
      FLYWAY_URL: jdbc:mysql://${RUTA_DB}:${PUERTO_DB}/${NOMBRE_DB}?allowPublicKeyRetrieval=true
      FLYWAY_USER: ${USUARIO_DB}
      FLYWAY_PASSWORD: ${CLAVE_ROOT_DB}
    entrypoint: ["flyway", "-connectRetries=60", "migrate"]
    depends_on: 
      - mysql