services:
  api:
    image: ncarvajalg/grupo-6-backend:v4.0.0
    container_name: g6_backend

    environment:
      - ARCHIVO_ENV=production
      - NODE_ENV=production

    ports:
      - "3000:5000"

    depends_on:
      - mysql

    env_file:
      - .env
    
  mysql:
    image: mysql:8.0.39-debian
    container_name: g6_backend_bd

    ports:
      - "3307:${PORT_DB}"

    volumes:
      - ./sql:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: grupo-6
      MYSQL_DATABASE: Paginas_Selectas
      
    env_file:
      - .env
    