export enum Encuadernacion {
  TAPA_DURA = 'Tapa dura',
  TAPA_BLANDA = 'Tapa blanda',
  ENCUADERNACION_ESPIRAL = 'Encuadernación en espiral',
  EDICION_BOLSILLO = 'Edición de Bolsillo',
  EDICION_LUJO = 'Edición de Lujo',
  DIGITAL = 'Digital',
  AUDIOLIBRO = 'Audiolibro',
  IMPRESION_BAJO_DEMANDA = 'Impresión Bajo Demanda',
  COLECCIONISTA = 'Coleccionista',
  EDICION_LIMITADA = 'Edición Limitada',
  RUSTICA = 'Rústica',
  LIBRETA_APUNTES = 'Libreta de Apuntes',
  MANUAL = 'Manual',
  GUIA_VIAJE = 'Guía de Viaje',
  COMIC = 'Cómic',
  MANGA = 'Manga',
  FOLLETO = 'Folleto',
  CALENDARIO = 'Calendario',
  POSTER = 'Póster',
  PLEGABLE = 'Plegable',
  TARJETA = 'Tarjeta',
}
