export enum EncuadernacionEnum {
  TAPA_DURA='Tapa Dura',
  TAPA_BLANDA='Tapa Blanda',
  EDICION_DE_BOLSILLO='Edición de Bolsillo',
  EDICION_DE_LUJO='Edición de Lujo',
  DIGITAL='Digital',
  AUDIOLIBRO='Audiolibro',
  IMPRESION_BAJO_DEMANDA='Impresión Bajo Demanda',
  COLECCIONISTA='Coleccionista',
  EDICION_LIMITADA='Edición Limitada',
  RUSTICA='Rústica',
  LIBRETA_DE_APUNTES='Libreta de Apuntes',
  MANUAL='Manual',
  GUIA_DE_VIAJE='Guía de Viaje',
  COMIC='Cómic',
  MANGA='Manga',
  FOLLETO='Folleto',
  CALENDARIO='Calendario',
  POSTER='Póster',
  PLEGABLE='Plegable',
  TARJETA='Tarjeta',
}
