export enum Genero {
  // Libros de ficción
  THRILLER = 'Thriller',
  NOVELA_HISTORICA = 'Novela histórica',
  ROMANCE = 'Romance',
  CIENCIA_FICCION = 'Ciencia ficción',
  DISTOPIA = 'Distópia',
  AVENTURA = 'Aventura',
  FANTASIA = 'Fantasía',
  COMTEMPORANEO = 'Contemporáneo',
  TERROR = 'Terror',
  PARANORMAL = 'Paranormal',
  POESIA = 'Poesía',
  JUVENIL = 'Juvenil',
  INFANTIL = 'Infantil',
  NOVELA = 'Novela',
  CLASICO = 'Clásico',

  // Libros de no-ficción
  AUTOAYUDA = 'Autoayuda',
  SALUD = 'Salud y deporte',
  TECNICOS = 'Técnicos y especializados',
  BIOGRAFIAS = 'Biografías y autobiografías',
  COCINA = 'Cocina',
  VIAJES = 'Viajes',
  ARTE = 'Arte',
  CIENCIA_MATEMATICA = 'Ciencia y matemáticas',
  COMPUTACION = 'Computación',
  DERECHO_POLITICA = 'Derecho y política',
  ECONOMIA = 'Economía y finanzas',
  HISTORIA = 'Historia',
  FILOSOFIA_RELIGION = 'Filosofía y religión',
  EDUCACION = 'Educación',
}
