export enum GeneroEnum {

  // Libros de ficción
  THRILLER = 'Suspenso',
  NOVELA_HISTORICA = 'Histórico',
  ROMANCE = 'Romance',
  CIENCIA_FICCION = 'Ciencia Ficción',
  DISTOPIA = 'Distópia',
  AVENTURA = 'Aventura',
  FANTASIA = 'Fantasía',
  COMTEMPORANEO = 'Contemporáneo',
  TERROR = 'Terror',
  PARANORMAL = 'Paranormal',
  POESIA = 'Poesía',
  JUVENIL = 'Juvenil',
  INFANTIL = 'Infantil',
  NOVELA = 'Novela',
  CLASICO = 'Clásico',
  POLICIACO = 'Policiaco',
  DRAMA = 'Drama',
  COMEDIA = 'Comedia',

  // Libros de no-ficción
  AUTOAYUDA = 'Autoayuda',
  SALUD = 'Salud y deporte',
  TECNICOS = 'Técnicos y especializados',
  BIOGRAFIAS = 'Biografía',
  COCINA = 'Cocina',
  VIAJES = 'Viajes',
  ARTE = 'Arte',
  CIENCIA_MATEMATICA = 'Ciencia y matemáticas',
  COMPUTACION = 'Computación',
  DERECHO_POLITICA = 'Derecho y política',
  ECONOMIA = 'Economía y finanzas',
  HISTORIA = 'Historia',
  RELIGION = 'Religión',
  FILOSOFIA = 'Filosofía',
  EDUCACION = 'Educativo',
  ENSAYO = 'Ensayo',
  POLITICA = 'Política',
}
