export enum GeneroEnum {
  CIENCIA_FICCION='Ciencia Ficción',
  ROMANCE='Romance',
  FANTASIA='Fantasía',
  HISTORICO='Histórico',
  AVENTURA='Aventura',
  SUSPENSO='Suspenso',
  TERROR='Terror',
  POLICIACO='Policiaco',
  DRAMA='Drama',
  COMEDIA='Comedia',
  AUTOAYUDA='Autoayuda',
  BIOGRAFIA='Biografía',
  ENSAYO='Ensayo',
  EDUCATIVO='Educativo',
  INFANTIL='Infantil',
  JUVENIL='Juvenil',
  PARANORMAL='Paranormal',
  RELIGION='Religión',
  POLITICA='Política',
  FILOSOFIA='Filosofía'
}
